### ISSUE TITLE
Par rapport à tes dotfiles 🧑‍🦲

### ISSUE THREAD

**Issue by ShawnHeyli** [ErrorTeaPot/.dotfiles#1]
j'ai tout lu mais j'ai pas compris comment tu feur ?

Signé 🤚🤚🤚🦵

**Comment by ErrorTeaPot** [comment]
Ah oui je l'ai pas précisé dans le README, en gros je fais tout à base de cramptés. D'abord tu les dl, tu les ajoutes à ton path, tu run et après tu peux stow les dotfiles.
